### PR TITLE
Bump runtime to 43

### PR DESCRIPTION
**Pull request by sugar700**

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
cc @Kekun

**Comment by Miepee** [comment]
@Kekun @KamilaBorowska is there any update on this?

**Comment by Kekun** [comment]
I'll try to take time to update the runtime to 46 in the upcoming weeks, sorry for being silent for so long.

**Comment by Kekun** [comment]
I just submitted https://github.com/flathub/com.github.Alcaro.Flips/pull/4 to supersede this one. Thanks for your contribution and again sorry for being absent for the last almost 2 years.

**Pull request closed without merging**
